#!/bin/bash
get_answer() {
  read -p "$1 (y/n)" answer
  if [ $answer = "y" ] || [ $answer = "yes" ]; then
    echo "true"
  else
    echo ""
  fi
}

if [ $(get_answer "Install vim-plug?") ]; then
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

directories=$(ls)
for item in $directories; do
  case $item in
    ".")    continue;;
    "..")   continue;;
    ".git") continue;;
    "old")  continue;;
    "install") continue;;
    *)
      dotmanager -d $item -c add -b old
  esac
done
