#!/bin/bash

get_answer() {
  read -p "$1 (y/n) " answer
  if [ $answer = "y" ] || [ $answer = "yes" ]; then
    echo "true"
  else
    echo ""
  fi
}

if [ $(get_answer "Install vim-plug?") ]; then
  curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

all_dirs=$(ls -d */)

for dir in $all_dirs; do
  case dir in
    old)
      continue;;
    *)
      dotmanager -c add -b old -d $dir
   esac
done
