#!/bin/bash

B='#00000000'  # blank
C='#00000000'  # clear ish

# ring color
D="$(i3-get-color i3wm_0D)00"

# text
T="$(i3-get-color i3wm_0D)ff"

# wrong
W="$(i3-get-color i3wm_08)ff"

# verifying
V="$(i3-get-color i3wm_01)ff"

i3lock \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T        \
--wrongcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
--screen 1            \
--blur 9              \
--clock               \
--indicator           \
--timestr="%H:%M"  \
--datestr=""
#--keylayout 2         \
