#!/bin/bash

source $HOME/.config/just-colors/cache/color-palette.sh

B="${base00}ff"
C=$B  # clear ish

# ring color
D=$B

# text
T="${base06}ff"

# wrong
W="${base08}ff"

# verifying
V="${base01}ff"

i3lock \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T        \
--wrongcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
--screen 4            \
--blur 9              \
--clock               \
--indicator           \
\
--timestr="%H:%M"  \
--datestr="" \
\
--veriftext="Wait..." \
--wrongtext="Nope!" \
--noinputtext="None"
