#!/bin/bash
set -o errexit

bg=$(i3-get-color i3wm_00)
sf=$(i3-get-color i3wm_0D)
nf=$(i3-get-color i3wm_01)

HISTORY="$HOME/.drun_history"
test -f "$HISTORY" || touch "$HISTORY"
INPUT=$(dmenu -nf $nf -nb $bg -sb $bg -sf $sf -fn 'monospace-12' $@ < "$HISTORY")

test -n "$INPUT"

# aliases
case "$INPUT" in
    duckduckgo)
        CMD="xdg-open https://duckduckgo.com" ;;
    ranger)
      CMD="$(echo $TERMINAL) -e ranger" ;;
    *)
        CMD="$INPUT" ;;
esac

# test if CMD exist in $PATH
hash $(echo "$CMD" | cut -f1 -d ' ')

# write input to history
if ! grep -q "$INPUT" "$HISTORY"; then
    echo "$INPUT" >> "$HISTORY"
    sort "$HISTORY" -o "$HISTORY" &
fi

exec $CMD
