#!/bin/zsh

############
# general
############

alias fuck="pkill -9"
alias reload!=". ~/.bashrc"
alias c="clear"
alias top="htop"
alias r="ranger"
alias n="nvim"
alias vim="nvim"
alias dm="dotmanager"
alias x="startx"

alias sp="sudo pacman"
alias spI="sudo pacman -S"
alias spR="sudo pacman -Rsc"
alias spU="sudo pacman -Syu"

alias sy="systemctl"
alias ssy="sudo systemctl"


############
# configs
############

alias i3config="nvim ~/.config/i3/config"
alias nvimconfig="nvim ~/.config/nvim/init.vim"

############
# ls, cd
############

alias ll="ls -lhA"
alias la="ls -A"
alias ..="cd .."
alias ~="cd ~"
# go usb flash
alias guf="cd /run/media/$(whoami)"
mkcd () { mkdir -p -- "$1" && cd -P -- "$1"; }

############
# git
############

alias ga="git add"
alias gd="git diff"
alias gp="git push"
alias gs="git status"
alias gc="git commit"
alias gaa="git add -A"
alias gpf="git push -f"
alias gcm="git commit -m"
alias gca="git commit --amend"
alias gl="git log --all --decorate --oneline --graph"
alias gauto="git add . && git commit -m 'auto-commit' && git push origin master"

############
# tor
############

alias torstart="service tor start"
alias torstop="service tor stop"

############
# printer
############

alias print_file="lpr -P Canon_MP280_series"
alias printer_list="lpstat -p -d"

############
# date
############

alias cal3='cal -3'
alias mytime='date +%H:%M:%S'
alias today='date +"%A, %B %-d, %Y"'
alias weeknum='date +%V'

############
# python-env
############

alias envstart="source venv/bin/activate"
alias envnew="virtualenv venv"
alias envstop="deactivate"
