#!/bin/zsh

PROMPT_COMMAND='history -a'

HISTSIZE=500000
HISTFILESIZE=100000

# avoid dublicate
HISTCONTROL="erasedups:ignoreboth"

export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"

bindkey "^k" history-search-backward
bindkey "^j" history-search-forward
