#!/bin/bash

if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
[ -d "$HOME/jdk" ] && PATH="$PATH:$HOME/jdk/bin"
[ -d "$HOME/go" ]  && export GOPATH=$HOME/go
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
PATH="$PATH:$GOPATH/bin"
export PATH
