#!/bin/bash

PROMPT_COMMAND=__prompt_command

__prompt_command() {
    local EXIT="$?"
    PS1=""

    local normal='\[\e[0m\]'
    local red='\[\e[0;31m\]'
    local green='\[\e[0;32m\]'
    local blue='\[\e[01;34m\]'

    local git_branch="$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/')"

    PS1+="${green}\u${blue}@\h:\w"
    PS1+="${git_branch}"
    PS1+="\n${green} └─"
    [[ $EXIT != 0 ]] && \
      PS1+="${red} $EXIT"
    PS1+=" $ ${normal}"
}
